name: DynaFish
main: me.menexia.dynafish.DynaFish
version: 0.1
description: Dynamite Fishing!
commands:
    dynafish:
        description: Enables or disables dynamite fishing.
        usage: dynafish
    df:
        description: Also enables or disables dynamite fishing.
        usage: df